sigma = 25
N_hard = 8 # block size
N_wien = 8 # block size
lambda_3d = 2.7 # 3d transform coefficient threshold
lambda_2d = 2.0 # 2d transform coefficient threshold
tau_hard = 2500 # 1st step distance threshold
tau_wien = 400 # 2nd step distance threshold
max_patch = 16
window_size = 39
speed_up = 3